"use client";

import type { GenerateComprehensiveReportOutput } from "@/ai/flows/schemas";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ListChecks } from "lucide-react";

interface ReportDisplayProps {
  report: GenerateComprehensiveReportOutput;
}

export default function ReportDisplay({ report }: ReportDisplayProps) {
  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="text-2xl font-bold text-primary">{report.reportTitle}</CardTitle>
        <CardDescription>Generated by TentBed Analyzer AI</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6 text-base">
        <div>
          <h3 className="mb-2 text-lg font-semibold text-foreground">Introduction</h3>
          <p className="text-muted-foreground">{report.introduction}</p>
        </div>
        <div>
            <h3 className="mb-2 flex items-center text-lg font-semibold text-foreground">
                <ListChecks className="mr-2 h-5 w-5 text-accent" />
                Key Findings
            </h3>
          <ul className="list-inside space-y-2 text-muted-foreground">
            {report.findings.map((finding, index) => (
              <li key={index} className="flex items-start">
                <span className="mr-2 mt-1 text-accent">&#8226;</span>
                <span>{finding.replace(/^\*/, '').trim()}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h3 className="mb-2 text-lg font-semibold text-foreground">Conclusion</h3>
          <p className="text-muted-foreground">{report.conclusion}</p>
        </div>
      </CardContent>
    </Card>
  );
}
